IngressRoute:
  dashboard:
    enabled: true
experimental:
  http3:
    enabled: false
globalArguments: null
image:
  pullPolicy: Always
  tag: v2.9
logs:
  general:
    level: INFO
ports:
  web:
    exposedPort: 8080
  metrics:
    expose: false
  traefik:
    expose: true
  websecure:
    expose: false